-- 기존 테이블 생성문
CREATE TABLE RESERVATION
(
    RESERVATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    SPACE_ID       INT NOT NULL,
    MEMBER_ID      INT NOT NULL,
    START_DATE     DATE,
    END_DATE       DATE,
    START_TIME     TIME,
    END_TIME       TIME,
    STATUS         ENUM ('APPL', 'ACCEPT', 'COMPLETE_PAYMENT'),
    INPUT_DT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SPACE_ID) REFERENCES SPACE (SPACE_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- STATUS 컬럼을 ENUM 타입으로 변경
ALTER TABLE RESERVATION
    MODIFY COLUMN STATUS ENUM ('APPL', 'ACCEPT', 'COMPLETE_PAYMENT');


ALTER TABLE RESERVATION
    CHANGE COLUMN DATE START_DATE DATE,
    ADD COLUMN END_DATE DATE;


use spaceHub;
SELECT *
FROM SPACE;

SELECT *
FROM Member;
SELECT *

FROM RESERVATION;

SELECT  *
FROM    PAID ;



