-- 기존 테이블 생성문
CREATE TABLE RESERVATION
(
    RESERVATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    SPACE_ID       INT NOT NULL,
    MEMBER_ID      INT NOT NULL,
    START_DATE     DATE,
    END_DATE       DATE,
    START_TIME     TIME,
    END_TIME       TIME,
    STATUS         ENUM ('APPLY', 'ACCEPT', 'COMPLETE_PAYMENT'),
    INPUT_DT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SPACE_ID) REFERENCES SPACE (SPACE_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);


-- STATUS 컬럼을 ENUM 타입으로 변경
ALTER TABLE RESERVATION
    MODIFY COLUMN STATUS ENUM ('APPLY', 'ACCEPT', 'COMPLETE_PAYMENT');


ALTER TABLE RESERVATION
    CHANGE COLUMN DATE START_DATE DATE,
    ADD COLUMN END_DATE DATE;

drop table RESERVATION;

use spaceHub;
SELECT *
FROM SPACE;

SELECT *
FROM Member;

SELECT *
FROM RESERVATION;



SELECT *
FROM PAID;


SELECT *
FROM SPACE
WHERE HOST_ID = 1;


SELECT R.*
     , S.TITLE
     , M.NICKNAME
FROM RESERVATION R
         JOIN MEMBER M ON M.MEMBER_ID = R.MEMBER_ID
         JOIN SPACE S ON S.SPACE_ID = R.SPACE_ID
WHERE R.SPACE_ID = 4

SELECT R.*
     , M.NICKNAME
FROM RESERVATION R
         LEFT JOIN MEMBER M ON M.MEMBER_ID = R.MEMBER_ID
WHERE SPACE_ID = 4 WHERE RESERVATION_ID = 25;

SELECT *
FROM SPACE;
SELECT *
FROM TYPE_LIST;

SELECT s.*, h.*, t.*
FROM SPACE s
         JOIN HOST h ON s.HOST_ID = h.HOST_ID
         JOIN TYPE_LIST t ON s.TYPE_LIST_ID = t.TYPE_LIST_ID
WHERE s.SPACE_ID = 3


SELECT R.*
     , S.TITLE
     , S.ADDRESS
FROM RESERVATION R
         LEFT JOIN SPACE S ON R.SPACE_ID = S.SPACE_ID
WHERE MEMBER_ID = 1

SELECT *
FROM MEMBER;
USE spaceHub;

SELECT R.*
     , S.TITLE
     , S.ADDRESS
FROM RESERVATION R
         LEFT JOIN SPACE S ON R.SPACE_ID = S.SPACE_ID
WHERE R.MEMBER_ID = 3;


SELECT *
FROM RESERVATION;

SELECT P.*
     , S.TITLE
FROM PAID P
         LEFT JOIN SPACE S ON P.SPACE_ID = S.SPACE_ID
WHERE P.MEMBER_ID = 3

ALTER TABLE RESERVATION
    MODIFY COLUMN STATUS ENUM ('APPLY', 'ACCEPT', 'CANCEL', 'COMPLETE_PAYMENT','REFUND');

SELECT  F.*
,       S.TITLE
FROM    FAVORITES F
LEFT JOIN SPACE S ON F.SPACE_ID = S.SPACE_ID
WHERE   F.MEMBER_ID = 3

SELECT * FROM PAID;


SELECT * FROM RESERVATION;
SELECT * FROM MEMBER;

DROP TABLE COMMENT_RE;

SELECT  C.*
,       S.MEMBER_ID
FROM    COMMENT C
LEFT JOIN SPACE S
ON      C.PARENT_ID = S.SPACE_ID
WHERE   S.MEMBER_ID = 3
AND     C.DIVISION = 'REVIEW';


SELECT  C.*
,       S.MEMBER_ID
,       M.NICKNAME
,       S.TITLE
FROM    COMMENT C
JOIN SPACE S ON      C.PARENT_ID = S.SPACE_ID
JOIN MEMBER M ON      S.MEMBER_ID = M.MEMBER_ID
WHERE   S.MEMBER_ID = 17
AND     C.DIVISION = 'QNA';


SELECT * FROM COMMENT;


ALTER TABLE PAID ADD COLUMN STATUS ENUM('COMP','REFUND');

SELECT  CR.*
,       TM.NICKNAME AS TARGET_NAME
,       M.NICKNAME
FROM    COMMENT_RE CR
JOIN    MEMBER TM ON CR.TARGET_ID = TM.MEMBER_ID
JOIN    MEMBER M ON CR.MEMBER_ID = M.MEMBER_ID
WHERE   CR.COMMENT_ID = 74
