SELECT *
FROM OPTION_LIST;

SELECT *
FROM TYPE_LIST;

# TYPE_LIST
ALTER TABLE TYPE_LIST
    ADD COLUMN ICON VARCHAR(50);


# SPACE
ALTER TABLE SPACE
    ADD COLUMN MEMBER_ID      INT NOT NULL ,
    ADD COLUMN ZONECODE       VARCHAR(100)   NOT NULL,
    ADD COLUMN ADDRESS        VARCHAR(100)   NOT NULL,
    ADD COLUMN EXTRA_ADDRESS  VARCHAR(100)   NOT NULL,
    ADD COLUMN DETAIL_ADDRESS VARCHAR(100)   NOT NULL,
    ADD COLUMN LATITUDE       DECIMAL(10, 6) NOT NULL,
    ADD COLUMN LONGITUDE      DECIMAL(11, 6) NOT NULL,
    ADD COLUMN FACILITY TEXT,
    ADD COLUMN FLOOR INT,
    ADD COLUMN PARKING_SPACE INT;

ALTER TABLE SPACE
    ADD Column TYPE_LIST_ID INT;
ALTER TABLE SPACE
    MODIFY COLUMN FK_




ALTER TABLE SPACE
    ADD COLUMN MEMBER_ID INT;
ALTER TABLE SPACE
    ADD CONSTRAINT FK_SPACE_MEMBER
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

# SPACE_CONFIGURATION
ALTER TABLE SPACE_CONFIGURATION
    CHANGE SPACE_CONFIGURATION_ID SPACE_CONFIGURATION_ID INT AUTO_INCREMENT;

ALTER TABLE SPACE_CONFIGURATION
    CHANGE LOCATION FULL_ADDRESS VARCHAR(100);

-- FILE 테이블
CREATE TABLE FILE
(
    FILE_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    PARENT_ID BIGINT       NOT NULL,                                         -- 관련 엔티티 ID (공간, 게시판, 공지사항 등)
    DIVISION  VARCHAR(50)  NOT NULL,                                         -- 엔티티 유형 (예: SPACE, BOARD, NOTICE 등)
    FILE_NAME VARCHAR(255) NOT NULL,                                         -- 파일 이름
    INPUT_DT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPLOAD_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP-- 업로드 시간
);

SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE SPACE;
