SELECT *
FROM OPTION_LIST;

SELECT *
FROM TYPE_LIST;

# SPACE
ALTER TABLE SPACE
    ADD COLUMN LATITUDE  DECIMAL(10, 6) NOT NULL,
    ADD COLUMN LONGITUDE DECIMAL(11, 6) NOT NULL,
    ADD COLUMN ZONECODE VARCHAR(100) NOT NULL,
    ADD COLUMN ADDRESS VARCHAR(100) NOT NULL,
    ADD COLUMN DETAIL_ADDRESS VARCHAR(100) NOT NULL,
    ADD COLUMN EXTRA_ADDRESS VARCHAR(100) NOT NULL;