SELECT *
FROM OPTION_LIST;

SELECT *
FROM TYPE_LIST;

# TYPE_LIST
ALTER TABLE TYPE_LIST
    ADD COLUMN ICON VARCHAR(50);


-- TYPE_LIST 테이블
CREATE TABLE TYPE_LIST
(
    TYPE_LIST_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(255),
    IS_ACTIVE    BOOLEAN DEFAULT TRUE
);

-- OPTION_LIST 테이블
CREATE TABLE OPTION_LIST
(
    OPTION_LIST_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME           VARCHAR(255),
    IS_ACTIVE      BOOLEAN DEFAULT TRUE
);

-- SPACE_CONFIGURATION 테이블
CREATE TABLE SPACE_CONFIGURATION
(
    SPACE_OPTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    SPACE_ID        INT NOT NULL,
    OPTION_ID       INT NOT NULL,
    FOREIGN KEY (SPACE_ID) REFERENCES SPACE (SPACE_ID),
    FOREIGN KEY (OPTION_ID) REFERENCES OPTION_LIST (OPTION_LIST_ID)
);

-- FILE 테이블
CREATE TABLE FILE
(
    FILE_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    PARENT_ID BIGINT       NOT NULL,
    DIVISION  VARCHAR(50)  NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    INPUT_DT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

# FK 제약사항 조건 없애기 / 만들기
SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;
