USE prj3p;

-- MEMBER 테이블
CREATE TABLE MEMBER
(
    MEMBER_ID     INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL         VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD      VARCHAR(100) NOT NULL,
    NICKNAME      VARCHAR(50)  NOT NULL,
    MOBILE        VARCHAR(20),
    PROFILE_IMAGE VARCHAR(100),
    AUTH          VARCHAR(20),
    PROVIDER      VARCHAR(20),
    PROVIDER_ID   VARCHAR(50),
    INPUT_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- BOARD 테이블(CATEGORY_ID 추가, 나중에 VIEWS DEFAULT 값 추가)
CREATE TABLE BOARD
(
    BOARD_ID    INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID   INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    TITLE       VARCHAR(100),
    CONTENT     TEXT,
    INPUT_DT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VIEWS       INT       DEFAULT 0,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
);

-- CATEGORY 테이블(BOARD_ID, DESCRIPTION 삭제)
CREATE TABLE CATEGORY
(
    CATEGORY_ID   INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50),
    INPUT_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT *
FROM BOARD
ORDER BY BOARD_ID DESC;
SELECT *
FROM CATEGORY
ORDER BY CATEGORY_ID DESC;


# BOARD에 CATEGORY_ID 컬럼 추가(CATEGORY 테이블 CATEGORY_ID 참조)
# CATEGORY에 BOARD_ID 컬럼 삭제
DROP TABLE CATEGORY;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE BOARD;
SET FOREIGN_KEY_CHECKS = 1;

# CATEGORY에 BOARD_ID 컬럼 삭제
ALTER TABLE CATEGORY
    DROP COLUMN BOARD_ID;


# CATEGORY 테이블 NAME -> CATEGORY_NAME 으로 변경
ALTER TABLE CATEGORY
    DROP COLUMN NAME;
ALTER TABLE CATEGORY
    ADD COLUMN CATEGORY_NAME VARCHAR(50);

# BOARD 테이블 CATEGORY 드랍
ALTER TABLE BOARD
    DROP COLUMN CATEGORY;

# CATEGORY 테이블 DESCRIPTION 드랍
ALTER TABLE CATEGORY
    DROP COLUMN DESCRIPTION;

#