USE prj3p;

-- MEMBER 테이블
CREATE TABLE MEMBER
(
    MEMBER_ID     INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL         VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD      VARCHAR(100) NOT NULL,
    NICKNAME      VARCHAR(50)  NOT NULL,
    MOBILE        VARCHAR(20),
    PROFILE_IMAGE VARCHAR(100),
    AUTH          VARCHAR(20),
    PROVIDER      VARCHAR(20),
    PROVIDER_ID   VARCHAR(50),
    INPUT_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- BOARD 테이블(CATEGORY_ID 추가, VIEWS DEFAULT 값 0 추가, UPDATA_DT의 ON UPDATE CURRENT_TIMESTAMP 조건 삭제)
CREATE TABLE BOARD
(
    BOARD_ID    INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID   INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    TITLE       VARCHAR(100),
    CONTENT     TEXT,
    INPUT_DT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VIEWS       INT       DEFAULT 0,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
);

-- CATEGORY 테이블(BOARD_ID, DESCRIPTION 삭제, NAME -> CATEGORY_NAME 으로 변경)
CREATE TABLE CATEGORY
(
    CATEGORY_ID   INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50),
    INPUT_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- FILE 테이블(FOREIGN KEY 제약 사항 삭제, DIVISION INT -> VARCHAR, 외래키 제약사항 삭제)
CREATE TABLE FILE_LIST
(
    FILE_LIST_ID INT PRIMARY KEY AUTO_INCREMENT,
    PARENT_ID    INT         NOT NULL,
    DIVISION     VARCHAR(10) NOT NULL,
    FILE_NAME    VARCHAR(100),
    INPUT_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);
# FOREIGN KEY (PARENT_ID, DIVISION) REFERENCES BOARD(BOARD_ID, (SELECT DIVISION FROM FILE_LIST WHERE DIVISION = 'BOARD'))

-- COMMENT 테이블(DIVISION 컬럼 ENUM -> VARCHAR로 변경)
-- RATE_SCORE INT 추가
CREATE TABLE COMMENT
(
    COMMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID  INT                     NOT NULL,
    PARENT_ID  INT,
    DIVISION   VARCHAR(10) NOT NULL,
    CONTENT    TEXT,
    RATE_SCORE INT,
    INPUT_DT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- COMMENT_RE 테이블
CREATE TABLE COMMENT_RE
(
    COMMENT_RE_ID INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID     INT NOT NULL,
    COMMENT_ID    INT NOT NULL,
    CONTENT       TEXT,
    INPUT_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT (COMMENT_ID)
);

-- FILE 테이블
CREATE TABLE FILE
(
    FILE_ID   INT PRIMARY KEY AUTO_INCREMENT,
    PARENT_ID INT NOT NULL,
    DIVISION  VARCHAR(10),
    FILE_NAME VARCHAR(100),
    INPUT_DT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT *
FROM BOARD
ORDER BY BOARD_ID DESC;
SELECT *
FROM CATEGORY
ORDER BY CATEGORY_ID DESC;
SELECT *
FROM FILE
ORDER BY FILE_ID DESC;
SELECT *
FROM COMMENT
ORDER BY COMMENT_ID DESC;

ALTER TABLE FILE
    ADD COLUMN MEMBER_ID INT NOT NULL REFERENCES MEMBER(MEMBER_ID);


# BOARD에 CATEGORY_ID 컬럼 추가(CATEGORY 테이블 CATEGORY_ID 참조)
# CATEGORY에 BOARD_ID 컬럼 삭제
DROP TABLE CATEGORY;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE BOARD;
SET FOREIGN_KEY_CHECKS = 1;
DROP TABLE FILE_LIST;

DROP TABLE FILE;


# CATEGORY에 BOARD_ID 컬럼 삭제
ALTER TABLE CATEGORY
    DROP COLUMN BOARD_ID;


# CATEGORY 테이블 NAME -> CATEGORY_NAME 으로 변경
ALTER TABLE CATEGORY
    DROP COLUMN NAME;
ALTER TABLE CATEGORY
    ADD COLUMN CATEGORY_NAME VARCHAR(50);

# BOARD 테이블 CATEGORY 드랍
ALTER TABLE BOARD
    DROP COLUMN CATEGORY;

# CATEGORY 테이블 DESCRIPTION 드랍
ALTER TABLE CATEGORY
    DROP COLUMN DESCRIPTION;

# COMMENT 테이블 DIVISION 테이블 ENUM -> VARCHAR로 변경
DROP TABLE COMMENT;

# BOARD 테이블 UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
ALTER TABLE BOARD
    MODIFY UPDATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

# SPACE 테이블 DROP하고 재생성
DROP TABLE SPACE;

# SPACE 테이블
CREATE TABLE SPACE
(
    SPACE_ID       INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID      INT NOT NULL,
    TYPE_LIST_ID   INT NOT NULL,
    TITLE          VARCHAR(100),
    SUB_TITLE      VARCHAR(200),
    ZONECODE       VARCHAR(100),
    ADDRESS        VARCHAR(200),
    DETAIL_ADDRESS VARCHAR(200),
    EXTRA_ADDRESS  VARCHAR(200),
    LATITUDE       DECIMAL(14, 10),
    LONGITUDE      DECIMAL(14, 10),
    INTRODUCE      TEXT,
    FACILITY       TEXT,
    NOTICE         TEXT,
    PRICE          INT,
    CAPACITY       INT,
    FLOOR          INT,
    PARKING_SPACE  INT,
    INPUT_DT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    FOREIGN KEY (TYPE_LIST_ID) REFERENCES TYPE_LIST (TYPE_LIST_ID)
);

ALTER TABLE COMMENT
ADD COLUMN RATE_SCORE INT;

SELECT PARENT_ID, FILE_NAME FROM FILE WHERE PARENT_ID = 50;
DESC FILE;