#홍빈

DROP TABLE AUTH;

ALTER TABLE MEMBER
    ADD COLUMN AUTH_NAME ENUM ('ADMIN', 'HOST', 'USER');

ALTER TABLE MEMBER
    ADD COLUMN WITHDRAWN CHAR(1) DEFAULT 'N';

SELECT *
FROM MEMBER;



ALTER TABLE MEMBER
   ADD COLUMN NAVER_ID VARCHAR(3000);

ALTER TABLE MEMBER
  DROP COLUMN NAVER_ID;

ALTER TABLE BOARD
    ADD COLUMN CATEGORY ENUM ('NOTICE', 'FAQ');

ALTER TABLE HOST
    ADD COLUMN EMAIL VARCHAR(50)  NOT NULL UNIQUE,
    ADD COLUMN PASSWORD VARCHAR(100) NOT NULL,
    ADD COLUMN NICKNAME  VARCHAR(50)  NOT NULL,
    ADD COLUMN MOBILE  VARCHAR(20),
    ADD COLUMN PROFILE_IMAGE VARCHAR(100),
    ADD COLUMN AUTH VARCHAR(20),
    ADD COLUMN AUTH_NAME ENUM ('HOST'),
    ADD COLUMN WITHDRAWN CHAR(1) DEFAULT 'N';

SELECT*
FROM HOST;


